---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev 
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~3.0
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:pulpo/gitops-helm-workshop
    ref: pulpo 
    path: cluster/charts/podinfo
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.0.5
    service:
      enabled: true
      type: ClusterIP
